### ISSUE TITLE
What would it take to remove the Julia dependency?

### ISSUE THREAD

**Issue by rabernat** [observingClouds/xbitinfo#245]
I just tried installing xbitinfo into a fairly standard linux environment, and it failed to install Julia

```
$ mamba install -c conda-forge xbitinfo
Could not solve for environment specs
The following package could not be installed
└─ xbitinfo   is installable and it requires
   └─ julia >=1.6.0,<1.8.0  with the potential options
      ├─ julia [1.6.1|1.6.2|1.6.3] would require
      │  └─ libgit2 [>=1.1.1,<1.2.0a0 |>=1.2.0,<1.3.0a0 ], which requires
      │     └─ openssl >=1.1.1k,<1.1.2a , which can be installed;
      └─ julia [1.6.3|1.6.4|...|1.7.3] would require
         └─ pcre2 >=10.37,<10.38.0a0 , which can be installed.
```

This got me thinking...installing a full Julia stack is an awfully heavy dependency for Python users if you just want to compress your data.

There are two alternatives that could be explored:
- Package a compiled binary library from the Julia code. This is what we would do if the library were written in C++, Rust, etc. It seems that this is what PackageComplier.jl is for? Looks like [creating a C library](https://julialang.github.io/PackageCompiler.jl/stable/libs.html#libraries) is supported.
- Port Bitinformation.jl to C, Rust, Numba, Cython, etc. or even 😱 vanilla Python. Inconvenient maybe, but certainly not impossible.

I'm curious if you've considered either of these options.

**Comment by observingClouds** [comment]
Hi @rabernat,
The interplay between python and Julia is indeed a bit of a headache, especially from the python side. We have actually ported a lot of the BitInformation.jl functionality to python.

To only install dependencies needed for the pure-python implementation, try using 
```mamba install -c conda-forge xbitinfo-python```

**Comment by lukeconibear** [comment]
Great question and answer, thank you!

I think the use of Julia by `xbitinfo` can cause LLVM compatibility or network issues.

Removing this dependency with `xbitinfo-python` is very helpful.

`xbitinfo` is an excellent library, thanks!

**Comment by milankl** [comment]
The python implementation is slower and has (for reasons I don't know or understand) large memory allocations. We sometimes therefore used the julia implementation to analyse the bitinformation of larger datasets.

For a 1GB array with float32 you technically only need to allocate a 32x2x2 uint64 array to count the bitpairs (00, 01, 10, 11) for every bitposition (32). When you want a signed (instead of biased) exponent the 1GB array can be changed in-place (considered unsafe) or needs to be copied, doubling the memory footprint. While this is what BitInformation.jl does, python apparently allocates more copies of the array which limits its use for larger datasets. I find python always very intransparent where it allocates memory but that's probably just me. I believe we should make this memory issue a priority so that with, say, 16GB memory you can also analyse the bitinformation of arrays >8GB.
